version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.18
    working_directory: ~/project/frontend
    steps:
      - checkout
      # look for existing cache and restore if found; otherwise, use fallback
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
            - v1-deps-
      # install dependencies
      - run:
          name: Install deps
          command: yarn install
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      # run test suite
      - run:
          name: Run tests
          command: yarn test

workflows:
  build-and-test:
    jobs:
      - build-and-test